namespace PsddfCs {
	public partial class Psddf {
		/// <summary>
		/// Create output files and open output streams.
		/// </summary>
		void Ifn () {
			/*
    eof = 0
    prev = 99

    OutputFilePath = 'p_temp_opt'
			*/
//			const string OutputFilePath = "p_temp_opt";
//			const string ContinuationFilePath = "temp_contfile";

			/*
    fname(1) = OutputFilePath(1:i) // '.pso'  ! Output/Calculations
    fname(2) = OutputFilePath(1:i) // '.psp'  ! Surface Elevation data
    fname(3) = OutputFilePath(1:i) // '.psc'  !!Stores the output from a previous simulation so that it can be restarted
    fname(4) = OutputFilePath(1:i) // '.pgc'  ! Compressible Foundation Results
    fname(5) = OutputFilePath(1:i) // '.pgd'  ! Dredged Material Results
    fname(6) = OutputFilePath(1:i) // '.rcy'  !!The file generated by PSDDF for use with the CAP model

    open(iout, file = fname(1))
    open(iplot, file = fname(2))
    open(igracf, file = fname(4))
    open(igradf, file = fname(5))
    open(recoveryout, file = fname(6))
			*/
			// Output/Calculations
			Io.OpenWrite(iout, OutputFilePath + ".pso");
			// Surface Elevation data
			Io.OpenWrite(iplot, OutputFilePath + ".psp");
			// Compressible Foundation Results
			Io.OpenWrite(igracf, OutputFilePath + ".pgc");
			// Dredged Material Results
			Io.OpenWrite(igradf, OutputFilePath + ".pgd");
			// The file generated by PSDDF for use with the CAP model
			Io.OpenWrite(recoveryout, OutputFilePath + ".rcy");

			/*
    if (ndata2 == 2) then  ! Output saving for continuation
        open(iouts, file = fname(3), form = 'unformatted', access = 'stream')
    endif
			*/
			if (IsNotSaveContinuation == 2) {
				// Output saving for continuation
				Io.OpenWrite(iouts, OutputFilePath + ".psc");
			}
				
			/*
    if (ndata1 == 2) then  ! For continuation file
        OutputFilePath = 'temp_contfile'
        i = 1
        do while (OutputFilePath(i:i) /= ' ' .and. OutputFilePath(i:i) /= '.')
            i = i + 1
        enddo
        i = i - 1;

        fname(3) = OutputFilePath(1:i) // '.psc'
        open(ins, file = fname(3), form = 'unformatted', access = 'stream')

        OutputFilePath = OutputFilePath(1:i) // '.psp'
        open(prev, file = OutputFilePath)
        do while (eof /= -1)
            read(prev, *, iostat = eof) void1, void2
            write(iplot, '(2f15.5)') void1, void2
        enddo
        close (prev)
    endif
			*/
			if (IsNewSimulation == 2) {
				// For continuation file
				Io.OpenRead(ins, ContinuationFilePath + ".psc");

				const int prev = 99;
				Io.OpenRead(prev, ContinuationFilePath + ".psp");
				while (!Io.EndOfFile(prev)) {
					// write(iplot, '(2f15.5)') void1, void2
					Io.WriteLine(
						iplot, 
						"{0,15:F5}{1,15:F5}", 
						Io.ReadDouble(prev), 
						Io.ReadDouble(prev));
				}
				Io.CloseRead(prev);
			}
		}
	}
}

