namespace PsddfCs {
	public partial class Psddf {
		/// <summary>
		/// Init status
		/// </summary>
		public void EndSimulation () {
			// Output/Calculations
			Io.CloseWrite(OUT);
			// Surface Elevation data
			Io.CloseWrite(PLOT);
			// Compressible Foundation Results
			Io.CloseWrite(GCF);
			// Dredged Material Results
			Io.CloseWrite(GDF);
			// The file generated by PSDDF for use with the CAP model
			Io.CloseWrite(RCY);

			DredgedFillDesiccationDelayDays = DredgedFillInitialDesiccationDelayDays;
			DredgedFillDesiccationDelayMonths = DredgedFillInitialDesiccationDelayMonths;
		}
	}
}
